### ISSUE TITLE
Create variables editor like environment variables

### ISSUE THREAD

**Issue by lechuckroh** [lechuckroh/task-intellij-plugin#4]
Feedback from @mkyc in #2 

1. if that is possible then window to edit variables same as environment variables would be nice.
2. I would move "Variables" input under "Variables" label same as you did with environment variables.

<img width="464" alt="149664098-d698c0da-8315-4a48-8565-69f979256c87" src="https://user-images.githubusercontent.com/9215260/149682688-3d2cbdbe-9175-4902-9a53-c18ab3b0d5bc.png">

**Comment by mkyc** [comment]
@lechuckroh if that is complicated then I think you can really skip point 1 TBH. I didn't know that those are different editors, so I would just do point 2 🙂

**Comment by lechuckroh** [comment]
@mkyc 
Environment variables editor offers separate tables for user environment variables and system environment variables.
Variables editor needs only key-value table editor which is not provided by SDK. I have to implement the table with Java Swing API. 😢 

As for point 2, IntelliJ SDK doesn't provide a direct API to do this. 😭 

I'm studying Java Swing again after 10 years... I need some time. 😎

**Comment by mkyc** [comment]
Hahaha, man, I didn't know it's that much effort! I really do not think it's that important. If you feel that it is making you sad please do not force yourself 😸

**Comment by lechuckroh** [comment]
@mkyc  It's my pleasure to sharpen my old knowledge sometimes. 😄

**Comment by lechuckroh** [comment]
@mkyc You can try v1.4.0 [here](https://github.com/lechuckroh/task-intellij-plugin/releases/tag/v1.4.0)
![screenshot](https://user-images.githubusercontent.com/9215260/150238300-0c3a7d0e-9628-4a69-9909-8a1142c53b5e.png)

**Comment by mkyc** [comment]
@lechuckroh I'm testing it for last 3 hours and it looks and works great! 

I will have one more issue, but it requires bit more testing, so I will create it in couple hours.
